import { Project } from './types';

export const projects: Project[] = [
  {
    id: '4lkj34256hgfajdfs32',
    title: 'lottery Smart Contract development 🛠️',
    src: 'InsightFulDoc-SAAS.png',
    color: '#ddd6fe',
    url: 'https://github.com/Taaani/lottery_project_solidity',
    tech: ['Remix IDE','hardhat','metaMask wallet',"Renkiby ethereum" ],
    about: 'A smart contract Created in solidity langauge its explain the core concept of ethereum blockchain ',
    role: 'Blockchain',
  },
  {
    id: '4lkj34256hgf',
    title: 'Core developement of blockchain 📝',
    src: 'Learn-Wise.png',
    color: '#ffedd5',
    url: 'https://github.com/Taaani/core-development-of-blockchain',
    tech: ['javaScript','hashing sha256', ],
    about: 'A learning project where i learn about the whole working of blockchain',
    role: 'Fullstack',
  },

  {
    id: '4lkj34256hgf',
    title: 'Learn Wise 📝',
    src: 'Learn-Wise.png',
    color: '#ffedd5',
    url: 'https://learn-wise.vercel.app/',
    tech: ['NextJs-14','Shadcn-ui', 'PostgreSQL','Prisma','Zustand-State-Managment','Mux','Stripe','Uploadthing'],
    about: 'A learning managment application where you can buy and sell courses',
    role: 'Fullstack',
  },
  {
    id: '4lkj342dvd53',
    title: 'Idea Script 📼',
    src: 'Idea_Script.png',
    color: '#ecfccb',
    url: 'https://idea-script.vercel.app/',
    tech: ['NextJs-14', 'Shadcn-ui','Convex-DB', 'Clerk-Auth','Edge-Store'],
    about: 'Real time idea managment app',
    role: 'Fullstack',
  },
  {
    id: '4lkj34224',
    title: 'Events Lab 🔖',
    src: 'EventsLAB.png',
    color: '#dbeafe',
    url: 'https://eventlab.netlify.app/',
    tech: ['React', 'Firebase'],
    about: 'Find the Latest events near you and Book it with dashoard',
    role: 'Fullstack',

  },
  {
    id: '4lkj342dfd',
    title: 'EatingOut 🍴',
    src: 'eatingOut.png',
    color: '#ddd6fe',
    url: 'https://eatingout-reactapp.netlify.app/',
    tech: ['React', 'Framer', 'Firebase'],
    about: 'Resturent App order food and track the file with dashbaord',
    role: 'Frontend',
  },
  {
    id: '4lkj342wf33',
    title: 'Trend Blend 🛒',
    src: 'TrendBlend.png',
    color: '#fae8ff',
    url: 'https://trendblend.netlify.app/',
    tech: ['React', 'Node.js', 'Express', "Framer", "MongoDB", "RestAPI"],
    about: 'Ecommerece App with CMS',
    role: 'Fullstack',
  },
  {
    id: '4lkj34223rf',
    title: 'Url Shortner 🔗',
    src: 'ShortUrl.png',
    color: '#fee2e2',
    url: 'https://learnwithfaizan.netlify.app/',
    tech: ['React', "EJS", "Node.js", 'Express', "MongoDB", "RestAPI", 'Render', 'vercel'],
    about: 'You can short your URLS',
    role: 'Backend ',
  },
  {
    id: '4lkj3423f33',
    title: 'FileLinker 📩',
    src: 'fileLinker.png',
    color: '#dbeafe',
    url: 'https://file-linker.vercel.app/',
    tech: ['React', 'Firebase', 'ChakraUi','Bootstrap','dayjs'],
    about: 'A FileSharing app to share your files with others',
    role: 'Fullstack',
  },
  
 
];

export const color: string[] = [
  "#F59E0B",
  "#65A30D",
  "#EA580C",
  "#C026D3",
  "#14B8A6",
  "#E11D48",
  "#e09f3e",
  "#8338ec",
  "#ff9f1c",
  "#003d5b",
  "#0E9a5b",
  "#ff8a5b",
  "#008a5b",
];